version: "1.0"
stages:
 - "clone"
 - "build"
 - "test"
 - "deploy"
steps:

clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    git: "github"
    stage: "clone"
    
 build:
    title: "Building Docker image"
    type: "build"
    image_name: "bitnami/odoo"
    working_directory: "./odoo"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
 
 deploy:
    type: "helm"
    working_directory: "./odoo"
    arguments:
      action: "install"
      chart_name: "odoo"
      release_name: "first"
      helm_version: 3.0.2
      kube_context: "cluster-1@devops"
    stage: "deploy"
