

version: '1.0'
stages:
  - checkout
  - build
  - test
steps:
  clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      revision: '${{CF_REVISION}}'
      git: github  
  MyAppDockerImage:
    registry: docker.io
    title: Building Docker Image
    stage: build
    type: build
    working_directory: '${{clone}}'
    arguments:
      image_name: odoo
      tag: 'master'
      dockerfile: Dockerfile
  StoreChart:
    title: Storing Helm Chart
    type: helm
    stage: store
    working_directory: ./odoo
    arguments:
      action: push
      chart_name: charts/odoo
      kube_context: 'cluster-1@devops'
  DeployMyChart:
      type: helm
      stage: deploy
      working_directory: ./odoo
      arguments:
        action: install
        chart_name: charts/odoo
        release_name: odoo1
        helm_version: 3.0.2
        kube_context: 'cluster-1@devops'
        namespace: odoo-prod
        custom_values_files:
          - /values.yaml
        





























